### ISSUE TITLE
[Website] Fix CSS for mobile

### ISSUE THREAD

**Issue by feitnomore** [kubevirt-manager/kubevirt-manager.github.io#18]
The bottom bar is not showing correctly on mobile. The icons for Github, Youtube and Twitter are getting messed up.

**Comment by Jainex17** [comment]
Hey @feitnomore can i work on this?

**Comment by feitnomore** [comment]
Of course, please! I am terrible at CSS.

**Comment by feitnomore** [comment]
@Jainex17 , also, if you could evaluate the possibility of doing some CSS cleanup, it would be great.   
I am pretty sure there is code that is not used anywhere.

**Comment by Jainex17** [comment]
I have done what I can do in this PR #19 

I hope you take a look at it.

**Comment by feitnomore** [comment]
<img width="2640" alt="image" src="https://user-images.githubusercontent.com/41125128/213756678-23470e75-ed24-4ccf-ad19-6b0f9c0c773b.png">

I have a few concerns with this PR.   

- The Copyright information is missing.
- The License information is missing.
- Copying the same text as the `hero` makes it repetitive
- The footer is not always at the end of the page as you can see on the attached image
  
Thanks

**Comment by Jainex17** [comment]
OK, I'll make the changes.

**Comment by Jainex17** [comment]
Fixed following issue

✅The Copyright information is missing.
✅The License information is missing.
✅The footer is not always at the end of the page as you can see on the attached image
❌Copying the same text as the hero makes it repetitive (I am uncertain about what text to place there, but you can change it.)

**Comment by Jainex17** [comment]
hey @feitnomore Is there anything I still need to fix in this? #19
